apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipcontext-service-deployment
  labels:
    app: ipcontext-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipcontext-service
  template:
    metadata:
      labels:
        app: ipcontext-service
    spec:
      containers:
        - name: ipcontext-service
          image: diegof0/ipcontext-service:latest
          ports:
            - containerPort: 8080