apiVersion: v1
kind: Pod
metadata:
  name: ipcontext-service-pod
  labels:
    app: ipcontext-service
spec:
  containers:
    - name: ipcontext-service
      image: diegof0/ipcontext-service:latest
      ports:
        - containerPort: 8080