apiVersion: v1
kind: Pod
metadata:
  name: api-example-pod
  labels:
    app: api-example
spec:
  containers:
    - name: api-example
      image: diegof0/api-example:latest
      ports:
        - containerPort: 8080